config/routes.rb
Rails.application.routes.draw do
  get 'survivors/index'
  get 'cards/show'
  get '/search',to: "survivors#search"
  resources :resources
  resources :trades, only:[:index, :show]
  resources :order_items
  resource :cards, only:[:show]
  get "/infected_percentage", to: "survivors#infected_percentage"
  resources :survivors do
    member do
      put "like" => "survivors#upvote"
      put "unlike" => "survivors#downvote"
    end
  end
  root to:'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/survivor.rb
class Survivor < User
    acts_as_votable
end

app/controllers/survivors_controller.rb
class SurvivorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_survivor, only:[:upvote, :downvote]

  def index
    @survivors = Survivor.all
    @currentUser = current_user.id
  end

  def show
    @survivors = Survivor.all
  end

  def search
    @survivors = Survivor.where("name LIKE ?", "%" + params[:q] + "%")
  end

  def upvote
    @survivor.upvote_from current_user
    if @survivor.get_upvotes.size >= 5
      @survivor.update(:infected => true)
    else
      @survivor.update(:infected => false)
    end
    redirect_to survivors_index_path
  end

  def downvote
    @survivor.downvote_from current_user
    redirect_to survivors_index_path
  end

  def infected_percentage
    survivors=Survivor.where(infected: true).count
    total = Survivor.count
    @survivors = survivors.to_f / total.to_f * 100
  end
  helper_method :infected_percentage
  helper_method :uninfected_percentage

  def uninfected_percentage
    survivors=Survivor.where(infected: false).count
    total = Survivor.count
    @survivors = survivors.to_f / total.to_f * 100
  end

  private
  def set_survivor
    @survivor = Survivor.find(params[:id])
  end
end

app/helpers/survivors_helper.rb
module SurvivorsHelper
end

app/views/survivors/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background: black">
    <a class="navbar-brand logo-font" style="color: red; font-size: 30px;" href="#">Deathlok Survival</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto my-2 my-lg-0">
       <li class="nav-item">
            <p class="nav-link">
             <%= link_to "Home", :root %>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Trades", trades_path%>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Survivors", survivors_index_path %>
            </p>
        </li>
      </ul>
      <form class="form-inline" action="/search">
    <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search <i class="fa fa-search"></i></button>
  </form>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-list-4">
        <ul class="navbar-nav">
        <li class="nav-item dropdown dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.avatar_thumbnail , size: "40x40")%>   
          </a>
          <ul
          class="dropdown-menu dropdown-menu-end p-2"
          aria-labelledby="navbarDropdownMenuLink"
          >
          <li>
            <%= current_user.email%>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Edit Account", edit_user_registration_path%></a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>
          </li>
          </ul>
        </li>   
        </ul>
        </div>
      </div>
    </div>
</nav>

<div class="text-center center">
  <h2>Survivors List</h2>
  <br />
    <div class="row">
    <% @survivors.each do |survivor| %>
     <% if survivor.name != "Admin"%>
     <% if survivor.id != @currentUser %>
        <div class="col-md-3 col-xs-6 " style="background: black">
            <div class="icon">
                <br />
                <div class="thumbnail" > 
                    <%= image_tag(survivor.avatar, style: "width: 200px; height: 200px")%>
                </div>
                <div class="caption">
                    <h3><%= survivor.name%></h3>      
                    <p><%= survivor.email%></p>                 
                </div>
                 <%= link_to like_survivor_path(survivor), class:"like", method: :put do%>
                 <button class="btn btn-outline-danger"><i class='fas fa-skull-crossbones' ></i> Infected 
                 <span><%= survivor.get_upvotes.size%></span>
                </button>
                <%end%>

                <%= link_to unlike_survivor_path(survivor), class:"like", method: :put do%>
                  <button class="btn btn-outline-success" style=""><i class="fa fa-shield" aria-hidden="true"></i> Uninfected 
                  <span><%= survivor.get_downvotes.size%></span>
                  </button>
                <%end%>
                <br />
          </div>
        </div>
        <% end %>
      <% end %>
      <%end%>
    </div>
</div>

app/views/survivors/infected_percentage.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background: black">
    <a class="navbar-brand logo-font" style="color: red; font-size: 30px;" href="#">Deathlok Survival</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto my-2 my-lg-0 ">
       <li class="nav-item">
            <p class="nav-link">
             <%= link_to "Home", :root %>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Resources", resources_path%>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
              <%= link_to "Report",infected_percentage_path %>
            </p>
        </li>
      </ul>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-list-4">
        <ul class="navbar-nav">
        <li class="nav-item dropdown dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.avatar_thumbnail , size: "40x40")%>   
          </a>
          <ul
          class="dropdown-menu dropdown-menu-end p-2"
          aria-labelledby="navbarDropdownMenuLink"
          >
          <li>
            <%= current_user.email%>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Edit Account", edit_user_registration_path%></a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>
          </li>
          </ul>
        </li>   
        </ul>
        </div>
      </div>
    </div>
    
  </nav>
<div class="text-center">
<div class="d-flex justify-content-around text-danger">
    <h1>Generated Report</h1>
    <i class="fa fa-bar-chart" style="font-size: 38px" aria-hidden="true"></i>
</div>
<br />
<h3>
    Percentage of Infected users: <span class="text-danger"><%= infected_percentage.to_i %>%</span>
</h3>
<br />
<h3>
    Percentage of Uninfected users: <span class="text-success"><%= uninfected_percentage.to_i %>%</span>
</h3>
</div>

app/views/survivors/search.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background: black">
    <a class="navbar-brand logo-font" style="color: red; font-size: 30px;" href="#">Deathlok Survival</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto my-2 my-lg-0">
       <li class="nav-item">
            <p class="nav-link">
             <%= link_to "Home", :root %>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Trades", trades_path%>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Survivors", survivors_index_path %>
            </p>
        </li>
      </ul>
      <form class="form-inline" action="/search">
    <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search <i class="fa fa-search"></i></button>
  </form>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-list-4">
        <ul class="navbar-nav">
        <li class="nav-item dropdown dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.avatar_thumbnail , size: "40x40")%>   
          </a>
          <ul
          class="dropdown-menu dropdown-menu-end p-2"
          aria-labelledby="navbarDropdownMenuLink"
          >
          <li>
            <%= current_user.email%>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Edit Account", edit_user_registration_path%></a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>
          </li>
          </ul>
        </li>   
        </ul>
        </div>
      </div>
    </div>
</nav>

<div class="text-center center">
  <h1>Searched Results</h1>
<div class="row">
    <% @survivors.each do |survivor| %>
     <% if survivor.name != "Admin"%>
        <div class="col-md-3 col-xs-6 " style="background: black">
            <div class="icon">
                <div class="thumbnail" > 
                    <%= image_tag(survivor.avatar, style: "width: 200px; height: 200px")%>
                </div>
                <div class="caption">
                    <h3><%= survivor.name%></h3>      
                    <p><%= survivor.email%></p>                 
                </div>
                 <%= link_to like_survivor_path(survivor), class:"like", method: :put do%>
                <button class="btn btn-outline-success" style=""><i class="fa fa-shield" aria-hidden="true"></i> Uninfected 
                <span><%= survivor.get_upvotes.size%></span>
                </button>
                <%end%>

                <%= link_to unlike_survivor_path(survivor), class:"like", method: :put do%>
                  <button class="btn btn-outline-danger"><i class='fas fa-skull-crossbones' ></i> Infected 
                  <span><%= survivor.get_downvotes.size%></span>
                  </button>
                <%end%>
                <br />
            </div>
        </div>
        <% end %>
      <% end %>
    </div>
</div>