config/routes.rb
Rails.application.routes.draw do
  get 'survivors/index'
  get 'cards/show'
  get '/search',to: "survivors#search"
  resources :resources
  resources :trades, only:[:index, :show]
  resources :order_items
  resource :cards, only:[:show]
  get "/infected_percentage", to: "survivors#infected_percentage"
  resources :survivors do
    member do
      put "like" => "survivors#upvote"
      put "unlike" => "survivors#downvote"
    end
  end
  root to:'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background: black">
    <a class="navbar-brand logo-font" style="color: red; font-size: 30px;" href="#">Deathlok Survival</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto my-2 my-lg-0 ">
       <li class="nav-item">
            <p class="nav-link">
             <%= link_to "Home", :root %>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Resources", resources_path%>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
              <%= link_to "Report",infected_percentage_path %>
            </p>
        </li>
      </ul>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-list-4">
        <ul class="navbar-nav">
        <li class="nav-item dropdown dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.avatar_thumbnail , size: "40x40")%>   
          </a>
          <ul
          class="dropdown-menu dropdown-menu-end p-2"
          aria-labelledby="navbarDropdownMenuLink"
          >
          <li>
            <%= current_user.email%>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Edit Account", edit_user_registration_path%></a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>
          </li>
          </ul>
        </li>   
        </ul>
        </div>
      </div>
    </div>
    
  </nav>
  
<%= render 'main' %>

app/views/pages/_infected.html.erb
<nav class="navbar navbar-expand-lg navbar-dark d-flex justify-content-between" style="background: black">
    <a class="navbar-brand logo-font" style="color: red; font-size: 30px;" href="#">Deathlok Survival</a>
    <div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-list-4">
            <ul class="navbar-nav">
            <li class="nav-item dropdown dropleft">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag(current_user.avatar_thumbnail , size: "40x40")%>   
            </a>
            <ul
            class="dropdown-menu dropdown-menu-end p-2"
            aria-labelledby="navbarDropdownMenuLink"
            >
            <li>
                <%= current_user.email%>
            </li>
            <li>
                <a class="dropdown-item" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>
            </li>
            </ul>
            </li>   
            </ul>
            </div>
        </div>
        </div>
    </div>
  </nav>

  <section class="text-center">
    <h2>Sorry, You have been infected!!!</h2>
    <h1>¯\_(ツ)_/¯</h1>
  </section>

app/views/pages/_main.html.erb
<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://unanimous.ai/wp-content/uploads/ZOMBIES.png" alt="Los Angeles" width="100%" height="600vh">
      <div class="carousel-caption icon-background font-weight-bold">
        <h3 class="logo-font">Deathlok Survival</h3>
        <p>Organize before they rise!</p>
      </div>   
    </div>
    <div class="carousel-item">
      <img src="https://scenestr.com.au/media/k2/items/cache/ab670e509a40e4fa25acffc212a4e03b_XL.jpg" alt="Chicago" width="100%" height="600vh">
      <div class="carousel-caption icon-background font-weight-bold">
        <h3 class="logo-font">Zombie Apocalypse Survival</h3>
        <p> They feel no fear, why should you?</p>
      </div>   
    </div>
    <div class="carousel-item">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0KWKybF_aoxmb0cxLPH8cC-YoIdQ12OQfoMJbzZMQ_KXvVDLgYZrzj_WvQCndhJmTBBE&usqp=CAU" alt="New York" width="100%" height="600vh">
      <div class="carousel-caption icon-background font-weight-bold">
        <h3 class="logo-font">Deathlok Survival</h3>
        <p>Blades don't need reloading.</p>
      </div>   
    </div>
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

 
      <div class="mt-4 container marketing p-2 text-center">
      <h2>About Us</h2>
      <br/>
        <!-- Three columns of text below the carousel -->
        <div class="row">
          <div class="col-lg-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x icon-background"></i>
              <i class="fa fa-shopping-cart fa-stack-1x"></i>
            </span>
            <h2>Trade with Us</h2>
            <p class="text-justify">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-danger" style="background: rgb(197, 30, 30);" href="#" role="button">View details »</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x icon-background"></i>
              <i class="fa fa-search fa-stack-1x"></i>
            </span>
            <h2>Recognize Demolish</h2>
            <p class="text-justify">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
            <p><a class="btn btn-danger" style="background: rgb(197, 30, 30);"href="#" role="button">View details »</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x icon-background"></i>
              <i class="fa fa-user fa-stack-1x"></i>
            </span>
            <h2>Profile Setup</h2>
            <p class="text-justify">Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-danger" style="background: rgb(197, 30, 30);" href="#" role="button">View details »</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette section">
          <div class="col-md-7">
            <h2 class="featurette-heading">Trade with Us- <span class="icon-background">Organize before they rise!</span></h2>
            <p class="lead text-justify">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
           <%= image_tag("trade.jpg", height: 800, class:"featurette-image img-fluid mx-auto") %>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette section">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Recognize Demolish- <span class="icon-background">Blades don't need reloading.</span></h2>
            <p class="lead text-justify">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <%= image_tag("deathlok.jpg", height: 800, class:"featurette-image img-fluid mx-auto") %>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette section">
          <div class="col-md-7">
            <h2 class="featurette-heading">Update your profile <span class="icon-background">They feel no fear, why should you?</span></h2>
            <p class="lead text-justify">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <%= image_tag("safe.jpg", height: 800, class:"featurette-image img-fluid mx-auto") %>
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div>


<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity"> 
  <h2>Contact Us</h2>
  <div class="w3-xlarge w3-padding-32">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
 </div>
 <p>All right reserved</p>
</footer>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background: black">
    <a class="navbar-brand logo-font" style="color: red; font-size: 30px;" href="#">Deathlok Survival</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto my-2 my-lg-0">
      <li class="nav-item">
            <p class="nav-link">
             <%= link_to "Home", :root %>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Trades", trades_path%>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Survivors", survivors_index_path %>
            </p>
        </li>
      </ul>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-list-4">
        <ul class="navbar-nav">
        <li class="nav-item dropdown dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.avatar_thumbnail , size: "40x40")%>   
          </a>
          <ul
          class="dropdown-menu dropdown-menu-end p-2 bg-dark text-danger"
          aria-labelledby="navbarDropdownMenuLink"
          >
          <li>
            <%= current_user.email%>
          </li>
          <li>
            <a class="dropdown-item bg-dark text-danger" href="#"><%= link_to "Edit Account", edit_user_registration_path%></a>
          </li>
          <li>
            <a class="dropdown-item bg-dark text-danger" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>
          </li>
          </ul>
        </li>   
        </ul>
        </div>
      </div>
    </div>
    
  </nav>

app/views/pages/_survivor.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background: black">
    <a class="navbar-brand logo-font" style="color: red; font-size: 30px;" href="#">Deathlok Survival</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto my-2 my-lg-0">
       <li class="nav-item">
            <p class="nav-link">
             <%= link_to "Home", :root %>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Trades", trades_path%>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Survivors", survivors_index_path %>
            </p>
        </li>
      </ul>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-list-4">
        <ul class="navbar-nav">
        <li class="nav-item dropdown dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.avatar_thumbnail , size: "40x40")%>   
          </a>
          <ul
          class="dropdown-menu dropdown-menu-end p-2 bg-dark text-danger"
          aria-labelledby="navbarDropdownMenuLink"
          >
          <li>
            <%= current_user.email%>
          </li>
          <li>
            <a class="dropdown-item bg-dark text-danger" href="#"><%= link_to "Edit Account", edit_user_registration_path%></a>
          </li>
          <li>
            <a class="dropdown-item bg-dark text-danger" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>
          </li>
          </ul>
        </li>   
        </ul>
        </div>
      </div>
    </div>
    
  </nav>
  <%= render 'main' %>

app/views/pages/home.html.erb
<% if current_user %>
    <% if  current_user.email == "admin@gmail.com"%>
    <div class="alert alert-success alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong>Welcome!</strong> You are Signed in as Admin
    </div>
    <%= render 'admin' %>
    <% elsif current_user.infected %>
    <div class="alert alert-success alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong>Welcome!</strong> You are Signed in as Infected
    </div>
    <%= render 'infected' %>
    <%else%>
    <div class="alert alert-success alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong>Welcome!</strong> You are Signed in as Survivor
    </div>

    <%= render 'survivor' %>
  <%end%>

<% else %>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background: black">
  <a class="navbar-brand logo-font text-danger" style="font-size: 40px;" href="#">Deathlok Survival</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto my-2 my-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>
    </ul>
      <div class="my-2 my-lg-0">
        <button class="btn btn-outline-danger my-2 my-sm-0" type="submit"><%= link_to "Sign In", new_user_session_path %></button>
        <button class="btn btn-outline-danger my-2 my-sm-0" type="submit"><%= link_to "Create Account", new_user_registration_path%></button>
      </div>
    </div>
  </nav>
  <%= render 'main' %>

<% end %>