config/routes.rb
Rails.application.routes.draw do
  get 'survivors/index'
  get 'cards/show'
  get '/search',to: "survivors#search"
  resources :resources
  resources :trades, only:[:index, :show]
  resources :order_items
  resource :cards, only:[:show]
  get "/infected_percentage", to: "survivors#infected_percentage"
  resources :survivors do
    member do
      put "like" => "survivors#upvote"
      put "unlike" => "survivors#downvote"
    end
  end
  root to:'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/_form.html.erb
<div class="text-center container">
<h2>Add new Resources</h2>
<h1 class="h3 mb-3 font-weight-normal">Please enter details</h1>

<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row">
    <%= form.label :item_name %>
    <%= form.text_field :item_name, class:"form-control"  %>
  </div>

  <div class="field row">
    <%= form.label :points %>
    <%= form.number_field :points, class:"form-control"  %>
  </div>
  <br />
  <div class="field row">
  <%= form.label :image%> <br/>
  <%= form.file_field :image %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit "Create Resource" , class:"btn btn-lg btn-danger btn-block red-back"  %>
  </div>
  <%= link_to 'Back', resources_path %>
<% end %>

</div>

app/views/resources/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background: black" >
    <a class="navbar-brand logo-font" style="color: red; font-size: 30px;" href="#">Deathlok Survival</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto my-2 my-lg-0">
       <li class="nav-item">
            <p class="nav-link">
             <%= link_to "Home", :root %>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
            <%= link_to "Resources", resources_path%>
            </p>
        </li>
        <li class="nav-item">
            <p class="nav-link">
              <%= link_to "Report",infected_percentage_path %>
            </p>
        </li>
      </ul>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-list-4">
        <ul class="navbar-nav">
        <li class="nav-item dropdown dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.avatar_thumbnail , size: "40x40")%>   
          </a>
          <ul
          class="dropdown-menu dropdown-menu-end p-2"
          aria-labelledby="navbarDropdownMenuLink"
          >
          <li>
            <%= current_user.email%>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Edit Account", edit_user_registration_path%></a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></a>
          </li>
          </ul>
        </li>   
        </ul>
        </div>
      </div>
    </div>
    
  </nav>

app/views/resources/edit.html.erb
<%= render 'form', resource: @resource %>

app/views/resources/index.html.erb
<%= render 'navbar' %>

<div class="d-flex justify-content-around">
  <h1>Add Resources</h1>
    <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">
        <i class="fa fa-plus"></i>
        <%= link_to 'New Resource', new_resource_path %>
    </button>
</div>
<br />
<div class="text-center center">
    <div class="row">
    <% @resources.each do |resource| %>
        <div class="col-md-3 col-xs-6" style="background: black">
            <div class="icon">
                <div class="thumbnail" > 
                    <%= image_tag(resource.image, style: "width: 200px; height: 200px") if resource.image.attached?%>
                </div>
                <div class="caption">
                    <h3><%= resource.item_name%></h3>
                    <h5><%= resource.points %> points</h5>
                    <p><%= link_to 'Show', resource %> | 
                        <%= link_to 'Edit', edit_resource_path(resource) %> | 
                        <%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </p>
                </div>
            </div>
        </div>
      <% end %>
    </div>
</div>

app/views/resources/new.html.erb
<%= render 'form', resource: @resource %>

app/views/resources/show.html.erb
<%= render 'navbar' %>
<div class="card bg-dark">
  <div class="card-body">
    <div class="d-flex justify-content-around">
    <h3><%= @resource.item_name %></h3>
      <div>
        <%= link_to 'Edit', edit_resource_path(@resource) %> |
        <%= link_to 'Back', resources_path %>
      </div>
    </div>
  </div>
  <br />
  <div class="text-center">
      <p>
        <strong>Unit Points:</strong>
        <%= @resource.points %>
      </p>
      <p>
        <strong>Image:</strong>
        <%= image_tag(@resource.image, style: "width: 200px") if @resource.image.attached? %>
      </p>
  </div>
</div>