config/routes.rb
Rails.application.routes.draw do
  get 'survivors/index'
  get 'cards/show'
  get '/search',to: "survivors#search"
  resources :resources
  resources :trades, only:[:index, :show]
  resources :order_items
  resource :cards, only:[:show]
  get "/infected_percentage", to: "survivors#infected_percentage"
  resources :survivors do
    member do
      put "like" => "survivors#upvote"
      put "unlike" => "survivors#downvote"
    end
  end
  root to:'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  def show
    @order_items = current_order.order_items
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<%= link_to "#{current_order.order_items.size} resources with a points of #{current_order.subtotal }", cards_path%>

app/views/cards/_cards_item.html.erb
<%= render 'pages/navbar' %>
<% @order_items.each do |item| %>
    <div class="card bg-dark">
    <div class="card-body">
        <div class="d-flex justify-content-between">
            <div>
                <h3><%= item.resource.item_name %></h3>
                <h5>Unit Points: <%= item.resource.points %></h5>
                <%= form_for item, remote: true do |f| %>
                    <%= f.hidden_field :resource_id, :value => item.resource.id %>
                    <%= f.number_field :quantity, :value => item.quantity.to_i, class:"btn btn-outline-warning" %>
                    <%= f.submit "Update Card ", class:"btn btn-outline-warning" %>

                    <%= link_to "Remove Items", order_item_path(item), method: :delete, remote: true , class:"btn btn-outline-danger" %>

                <% end %>
                <br />
                <h2>Subtotal: <%= item.total %></h2>
            </div>
            <%= image_tag item.resource.image%>
        </div>
        
    </div>
    </div>
    <br/>
<% end %>

<h3 class="text-center text-success">Your current resources points has a Total of: <%= current_order.subtotal %></h3>
<br />

app/views/cards/show.html.erb
<div id="card-item">
<%= render 'cards_item'%>
</div>